package com.lld.imdb.constant;

public enum PersonaType {
    ACTOR,
    DIRECTOR,
    ASSISTANT_DIRECTOR,
    SCRIPT_WRITER,
    STORY_WRITER,
    PRODUCER,
    ASSISTANT_PRODUCER,
    MUSIC_DIRECTOR,
    CASTING_DIRECTOR,
    CAMERAMAN,
    STUNT_DIRECTOR,
    CINEMATOGRAPHER,
    PRODUCTION_DESIGN,
    ART_DIRECTOR,
    SET_DIRECTOR,
    COSTUME_DESIGNER,
    PRODUCTION_MANAGER,
    ARTIST,
    SOUND_ARTIST,
    STUNTMAN,
    ELECTRIC_HANDLER,
    WARDROBE_HANDLER,
    OTHER
}
